### ISSUE TITLE
clamapi pod not starting with tag 2.0.5

### ISSUE THREAD

**Issue by aeimer** [audig/clamapi#98]
Hi @audig,

I tried to update the clampi version from `2.0.4` to `2.1.0` and then to `2.1.5`, unfortunatley the pod won't start:

![grafik](https://user-images.githubusercontent.com/25035182/122417393-bb03f500-cf89-11eb-8bb8-d548684e767b.png)

How can we fix this issue?

BR Alex

**Comment by aeimer** [comment]
I investigated a bit and it seems like the version `2.0.4` was the last one working.
I tested the following versions and they do not seem like they are working:
- `2.0.5`
- `2.0.6`
- `2.1.0`
- `2.1.5`

**Comment by audig** [comment]
Sorry,
Due to this issues https://github.com/spring-projects/spring-boot/issues/22483 and deprecation of some configuration for liveness/readiness, there is an "404" error on liveness probe, cause liveness probe is not enabled.

I will fix this issue

**Comment by aeimer** [comment]
Cool! Thanks :)

Tell me if you need help 👍

**Comment by audig** [comment]
I will update the upstream chart to use by default this new version : 2.1.6

**Comment by audig** [comment]
Please comment if it doesn't work

**Comment by aeimer** [comment]
I already prepared a branch for it, but if you want go for it :D

Thanks for the quick fix 👍
